$JarPath="C:/Users/Alexander/Source/Minecraft/FabricMods/MagicMod/build/libs/magicmod-0.1-1.20.4.jar"
$ClientPath="C:/Users/Alexander/AppData/Roaming/com.modrinth.theseus/profiles/MinesFabricClient/mods"
$ServerPath="C:/Users/Alexander/AppData/Roaming/com.modrinth.theseus/profiles/MinesFabricServer/mods"
cp "$JarPath" "$ClientPath"
cp "$JarPath" "$ServerPath"
